First implementation of backlink testing.
nlbdev/nordic-epub3-dtbook-migrator pull request #509
Opened 2021-11-03 07:31 UTC by kalaspuffar

Trying to solve #478

2021-11-03 09:22 UTC, josteinaj requested changes
Looks good, should work. But I have some comments/questions.

2021-11-03 09:22 UTC, josteinaj commented on src/main/resources/xml/schema/2020-1/nordic2020-1.opf-and-html.sch
> +        <rule context="html:*[tokenize(@epub:type,'\s+')=('noteref')]">
I think noterefs is always `<a>`?

2021-11-03 09:22 UTC, josteinaj commented on src/main/resources/xml/schema/2020-1/nordic2020-1.opf-and-html.sch
> +            <assert test="count(//html:a[tokenize(@role,'\s+')='doc-backlink' and substring-after(@href,'#') = current()/@id]) &gt;= 1">[nordic_opf_and_html_30a] The <value-of
Can there be multiple backlinks or should this check for exactly one match?

2021-11-03 09:22 UTC, josteinaj commented on src/main/resources/xml/schema/2020-1/nordic2020-1.opf-and-html.sch
> +            <assert test="count(//html:*[tokenize(@epub:type,'\s+')=('noteref') and @id = current()/substring-after(@href,'#')]) &gt;= 1">[nordic_opf_and_html_30b] The backlink
Here also, I think noterefs are aways `<a>`.

And there should probably be just one noteref matching each backlink?

@martinpub I suppose a book might potentially have multiple noterefs referencing the same note. How do we handle backlinks in such cases?

2021-11-03 09:22 UTC, josteinaj commented on src/main/resources/xml/schema/2020-1/nordic2020-1.sch
> +            <!-- this is the single-HTML version of the rule; the multi-HTML version of this rule is in nordic2020-1.opf-and-html.sch -->
these single-HTML vs multi-HTML comments can probably be removed.

2021-11-03 15:07 UTC, kalaspuffar commented
Hi @josteinaj 

Thank you for the review. I've updated the code after your suggestions.

Best regards
Daniel

2021-11-04 13:03 UTC, josteinaj commented
Looks good!

@martinpub How should be handle backlinks in books with multiple noterefs referencing the same note? I assume that's not too uncommon?

2021-11-04 13:04 UTC, josteinaj commented on src/main/resources/xml/schema/2020-1/nordic2020-1.opf-and-html.sch
> +            <assert test="count(//html:*[tokenize(@epub:type,'\s+')=('noteref') and @id = current()/substring-after(@href,'#')]) &gt;= 1">[nordic_opf_and_html_30b] The backlink
(resolving this, asked here instead: https://github.com/nlbdev/nordic-epub3-dtbook-migrator/pull/509#issuecomment-960876785)

2021-11-04 13:04 UTC, josteinaj approved these changes

2022-03-18 10:18 UTC, josteinaj commented
I think we need to solve the case of multiple noterefs referencing the same note before we merge this.

2022-10-20 17:20 UTC, josteinaj commented
The conclusion is that there must be exactly one note reference for each note (see https://github.com/nlbdev/epub3-guidelines-update/issues/150).

2022-10-21 09:46 UTC, josteinaj requested changes
We should also change the annotation rules:
- Every annotation reference must have exacly one annotation
- Every annotation must have exactly one annotation reference

Other than that, I think it looks good.

2022-10-21 11:57 UTC, kalaspuffar commented
@josteinaj Made the requested text changes.

2022-11-01 11:54 UTC, josteinaj approved these changes

2022-11-08 11:56 UTC, erikmtm approved these changes

2022-11-09 10:10 UTC, josteinaj commented
Merged into `master` in 15daadbc5fc213b9327fc0ddaa2df7c4603332cf

2022-11-09 10:10 UTC, closed without merging