Add noteref role requirement.
nlbdev/nordic-epub3-dtbook-migrator pull request #525
Opened 2022-10-27 07:41 UTC by kalaspuffar

Hi @josteinaj 

I tried to solve: https://github.com/nlbdev/nordic-epub3-dtbook-migrator/issues/520

Have added requirements for the role, following the specification.

Best regards
Daniel

2022-10-27 13:33 UTC, kalaspuffar commented on src/main/resources/xml/schema/2020-1/nordic-html5.rng
> -        </optional>
Otherwise you'll get an error with it defined twice.

2022-10-27 13:34 UTC, kalaspuffar commented on src/main/resources/xml/schema/2020-1/nordic-html5.rng
> +    <define name="coreattrs.norole">
Correct, not used at the moment but I guess it could be useful in the future.

2022-11-01 11:11 UTC, josteinaj requested changes

2022-11-01 11:11 UTC, josteinaj commented on src/main/resources/xml/schema/2020-1/nordic-html5.rng
> -        </optional>
Ok, I see.

I think you also need to add the optional role reference into `<define name="attrs.base">`?

2022-11-02 06:54 UTC, kalaspuffar commented on src/main/resources/xml/schema/2020-1/nordic-html5.rng
> -        </optional>
Hi @josteinaj 

I tried it, but I got a validation error.

org.xml.sax.SAXParseException; systemId: file:/tmp/WebarchEPUB177267222121405526771135501326296843/nordic-html5.rng; lineNumber: 2805; columnNumber: 27; duplicate attribute "role"

If it were required, we would get validation errors on books where the role was present in places that weren't allowed.

I ran all the tests, and they passed, so it's probably correct.

Best regards
Daniel

2022-11-03 12:33 UTC, josteinaj commented on src/main/resources/xml/schema/2020-1/nordic-html5.rng
> -        </optional>
Oh, ok. Then I suppose I'm missing something and it's fine as you have done it.

2022-11-03 12:35 UTC, josteinaj approved these changes

2022-11-08 12:00 UTC, erikmtm approved these changes

2022-11-09 10:25 UTC, merged